In [43]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import product
from sklearn.decomposition import RandomizedPCA
from sklearn.datasets import fetch_mldata
from sklearn.utils import shuffle
from tensorflow.examples.tutorials.mnist import input_data
from sklearn import tree

print("Reading MNIST dataset")
mnist = input_data.read_data_sets('minst_data/')

train_images = mnist.train.images
train_labels = mnist.train.labels

images = list(mnist.train.images) + list(mnist.test.images)
labels = list(mnist.train.labels) + list(mnist.test.labels)
    
print("Done loading data")

Reading MNIST dataset
Extracting minst_data/train-images-idx3-ubyte.gz
Extracting minst_data/train-labels-idx1-ubyte.gz
Extracting minst_data/t10k-images-idx3-ubyte.gz
Extracting minst_data/t10k-labels-idx1-ubyte.gz
Done loading data


In [10]:
pca = RandomizedPCA(n_components=5)

C:\Users\Jay\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)


In [25]:
X_transformed = pca.fit_transform(images)

In [26]:
print(X_transformed)

[[ 0.70172006  2.46598864 -1.38122296  2.51256108  0.34788296]
 [ 0.40679073 -0.94392073 -0.57841569 -3.60376215  1.03602302]
 [-0.15079647  3.0315156  -2.1373868  -0.75222909  1.06591439]
 ..., 
 [-1.05701768  2.32230926  1.40450478 -1.66684675  2.60305882]
 [-1.20471632 -0.54051542  2.4513638  -1.12311316 -0.59851819]
 [ 4.15293264 -0.37876442  2.80509615  3.09990859  0.7316879 ]]


In [30]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_images, train_labels)

In [34]:
train_images = X_transformed[:len(train_images)]
test_images = X_transformed[len(train_images):]

In [36]:
predicted_labels = clf.predict(test_images)

In [39]:
from sklearn.metrics import accuracy_score
score = accuracy_score(mnist.test.labels, predicted_labels, normalize=True)
print("Accuracy Score: ", score)

Accuracy Score:  0.6681


In [51]:
pca_20 = RandomizedPCA(n_components=20)
X_transformed_20 = pca.fit_transform(images)

C:\Users\Jay\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class RandomizedPCA is deprecated; RandomizedPCA was deprecated in 0.18 and will be removed in 0.20. Use PCA(svd_solver='randomized') instead. The new implementation DOES NOT store whiten ``components_``. Apply transform to get them.
  warnings.warn(msg, category=DeprecationWarning)


In [52]:
train_images = X_transformed[:len(train_images)]
test_images = X_transformed[len(train_images):]
print(len(test_images[0]))

20


In [53]:
clf_20 = tree.DecisionTreeClassifier()
clf_20 = clf_20.fit(train_images, train_labels)

In [55]:
predicted_labels = clf_20.predict(test_images)

In [56]:
from sklearn.metrics import accuracy_score
score = accuracy_score(mnist.test.labels, predicted_labels, normalize=True)
print("Accuracy Score: ", score)

Accuracy Score:  0.8534
